random_seed: 42

# POSSIBLE ENVIRONMENTS:
# - CartPole-v1
# - Acrobot-v1
# - Pendulum-v0
# - BipedalWalker-v2
# - Walker2d-v2

environment:
  name: 'BipedalWalker-v2'
  n_runs_per_agent: 1
  animate: False

# GRADIENT BASED ALGORITHMS

episodes: 1000

ddpg:
  replay_start:
  buffer_size:
  batch_size: 32
  gamma: 0.99
  tau: 0.001
  actor_lr: 1e-4
  critic_lr: 1e-3
  n_episodes: 100000
  n_runs:


# EVOLUTIONARY ALGORITHMS

population:
  size: 50
  max_generations: 200

genetic_algorithm:
  perc_selected: 0.25
  mutation_rate: 0.2
  mutation_noise: 1
  elite: 3

evolution_strategies:
  learning_rate: 0.01
  noise: 0.01

cma_evolution_strategies:
  perc_selected: 0.25

results:
  path: 'results'
  scores: 'scores'
  weights: 'weights'

visualization:
  path: 'visualization'
  weights: 'weights'

logger: 'runs.yml'