random_seed: 42

# POSSIBLE ENVIRONMENTS:
# - CartPole-v1
# - BipedalWalker-v2
# - Walker2d-v2

environment:
  name: 'BipedalWalker-v2'
  max_time: 2000
  n_runs_per_agent: 2
  animate: False

genetic_algorithm:
  population_size: 50
  max_generations: 600
  n_selected: 0.3
  mutation_rate: 0.2
  mutation_noise: 1
  elite: 3

results:
  path: 'results'
  scores: 'scores'
  weights: 'weights'

visualization:
  path: 'visualization'
  weights: 'weights'

logger: 'logs.log'