random_seed:

# POSSIBLE ENVIRONMENTS:
# - CartPole-v1
# - Acrobot-v1
# - Pendulum-v0
# - BipedalWalker-v2
# - Walker2d-v2

environment:
  name: 'BipedalWalker-v2'
  n_runs_per_agent: 1
  animate: False

# GRADIENT BASED ALGORITHMS

ddpg:
  n_episodes: 3000
  buffer_size: 1000000
  batch_size: 128
  gamma: 0.99
  tau: 0.01
  actor_lr: 0.0001
  critic_lr: 0.001
  saved_weights:
    actor: 'actor.h5'
    critic: 'critic.h5'
    target_actor: 'target_actor.h5'
    target_critic: 'target_critic.h5'


# EVOLUTIONARY ALGORITHMS

population:
  size: 50
  max_generations: 200

genetic_algorithm:
  perc_selected: 0.25
  mutation_rate: 0.2
  mutation_noise: 1
  elite: 3

evolution_strategies:
  learning_rate: 0.01
  noise: 0.01

cma_evolution_strategies:
  perc_selected: 0.25

results:
  path: 'results'
  scores: 'scores'
  weights: 'weights'
  saved_models: 'saved_models'

visualization:
  path: 'visualization'
  weights: 'weights'

logger: 'runs.yml'