environments:

  - name: 'CartPole-v1'
    n_hidden_units:
      - 24
    activations:
      - 'relu'
      - 'softmax'

  - name: 'BipedalWalker-v2'
    n_hidden_units:
      - 48
      - 24
    activations:
      - 'tanh'
      - 'tanh'
      - 'tanh'

  - name: 'Walker2d-v2'
    n_hidden_units:  # https://arxiv.org/pdf/1710.06117.pdf
      - 50
      - 50
    activations:
      - 'relu'
      - 'relu'
      - 'softmax'
